ATTACH VIEW FactBwpzWeek
(
    `channel_level` Nullable(String), 
    `channel_code` Nullable(String), 
    `SPUKey` UInt64, 
    `bwpz_order` Nullable(Float32), 
    `爆旺平滞结果` Nullable(String), 
    `综合得分` Nullable(Float32), 
    `在架时长` Nullable(String), 
    `历史取数开始时间` Date, 
    `历史取数结束时间` Date, 
    `判定日期内销售天数` Nullable(Float32), 
    `销售额` Nullable(Float32), 
    `销售速度` Nullable(Float32), 
    `单件毛利额` Nullable(Float32), 
    `销售额标准化值` Nullable(Float32), 
    `速度标准化值` Nullable(Float32), 
    `单件毛利额标准化值` Nullable(Float32), 
    `销售额权重` Nullable(Float32), 
    `销售速度权重` Nullable(Float32), 
    `单件毛利额权重` Nullable(Float32), 
    `排名` Nullable(Float32), 
    `销售量` Nullable(Float32), 
    `平均成本` Nullable(Float32), 
    `判定爆旺平滞时间` Date
) AS
SELECT 
    channel_level, 
    channel_code, 
    m.id AS SPUKey, 
    bwpz_order, 
    bwpz AS `爆旺平滞结果`, 
    bwpz_score AS `综合得分`, 
    is_observed AS `在架时长`, 
    stage_st AS `历史取数开始时间`, 
    stage_ed AS `历史取数结束时间`, 
    days_online AS `判定日期内销售天数`, 
    pay_amt AS `销售额`, 
    sale_speed AS `销售速度`, 
    unit_profit AS `单件毛利额`, 
    pay_amt_norm AS `销售额标准化值`, 
    sale_speed_norm AS `速度标准化值`, 
    unit_profit_norm AS `单件毛利额标准化值`, 
    pay_amt_wt AS `销售额权重`, 
    sale_speed_wt AS `销售速度权重`, 
    unit_profit_wt AS `单件毛利额权重`, 
    rank AS `排名`, 
    pay_prd_qty AS `销售量`, 
    unit_cost AS `平均成本`, 
    judge_date AS `判定爆旺平滞时间`
FROM eva_huigou.opt_bwpz_result
ANY LEFT JOIN spl_huigou.mapping_keys AS m ON m.code = spu
