version: '2'
services:
  DEV:
    image: 'yandex/clickhouse-server:latest'
    restart: always
    ports:
      - 9000:9000
      - 9004:9004
      - 8123:8123
    volumes:
      - /var/lib/clickhouse/dev:/var/lib/clickhouse
      - /etc/clickhouse-server/dev/config.d:/etc/clickhouse-server/config.d
      - /etc/clickhouse-server/dev/users.d:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144 
        hard: 262144 
    privileged: true

  GA:
    image: 'yandex/clickhouse-server:latest'
    restart: always
    ports:
      - 9009:9000
      - 8129:8123
    volumes:
      - /var/lib/clickhouse/ga:/var/lib/clickhouse
      - /etc/clickhouse-server/ga/config.d:/etc/clickhouse-server/config.d
      - /etc/clickhouse-server/ga/users.d:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144 
        hard: 262144 
    privileged: true

