ATTACH TABLE ali_op_overall_op_logs
(
    `id` Int64, 
    `event_date` Nullable(Date), 
    `shop_code` Nullable(String), 
    `prd_id` Nullable(String), 
    `prd_name` Nullable(String), 
    `pc_expo_count` Nullable(Int64), 
    `visitor_count` Nullable(Int64), 
    `ws_visitor_count` Nullable(Int64), 
    `pc_click_count` Nullable(Int64), 
    `prd_page_jump_out_rate` Nullable(Float32), 
    `pc_prd_page_jump_out_rate` Nullable(Float32), 
    `ws_prd_page_jump_out_rate` Nullable(Float32), 
    `avg_stay_in_s` Nullable(Float32), 
    `ws_avg_stay_in_s` Nullable(Float32), 
    `pc_avg_stay_in_s` Nullable(Float32), 
    `pay_amt` Nullable(Float32), 
    `pc_visitor_count` Nullable(Int64), 
    `add_cart_prd_count` Nullable(Int64), 
    `pc_add_cart_prd_count` Nullable(Int64), 
    `ws_add_cart_prd_count` Nullable(Int64), 
    `fav_prd_buyer_count` Nullable(Int64), 
    `pc_fav_prd_buyer_count` Nullable(Int64), 
    `ws_fav_prd_buyer_count` Nullable(Int64), 
    `pc_pay_amt` Nullable(Float32), 
    `ws_pay_amt` Nullable(Float32), 
    `pay_prd_count` Nullable(Int64), 
    `pc_pay_prd_count` Nullable(Int64), 
    `ws_pay_prd_count` Nullable(Int64), 
    `pay_buyer_count` Nullable(Int64), 
    `pc_pay_buyer_count` Nullable(Int64), 
    `ws_pay_buyer_count` Nullable(Int64), 
    `avg_order_amt` Nullable(Float32), 
    `pc_avg_order_amt` Nullable(Float32), 
    `ws_avg_order_amt` Nullable(Float32), 
    `pay_cv_rate` Nullable(Float32), 
    `pc_pay_cv_rate` Nullable(Float32), 
    `ws_pay_cv_rate` Nullable(Float32), 
    `prd_pv_count` Nullable(Int64), 
    `ws_prd_pv_count` Nullable(Int64), 
    `pc_prd_pv_count` Nullable(Int64), 
    `success_return_amt` Nullable(Float32), 
    `order_buyer_count` Nullable(Int64), 
    `order_prd_count` Nullable(Int64), 
    `order_amt` Nullable(Float32), 
    `order_cv_rate` Nullable(Float32), 
    `item_no` Nullable(String), 
    `prd_status` Nullable(String), 
    `prd_tag` Nullable(String), 
    `add_buy_count` Nullable(Int64), 
    `pay_new_buyer_count` Nullable(Int64), 
    `pay_old_buyer_count` Nullable(Int64), 
    `old_buyer_pay_amt` Nullable(Float32), 
    `hot_pay_amt` Nullable(Float32), 
    `visitor_avg_value` Nullable(Float32), 
    `compete_score` Nullable(Float32), 
    `pay_amt_by_year` Nullable(Float32), 
    `pay_amt_by_month` Nullable(Float32), 
    `pay_count_by_month` Nullable(Float32), 
    `search_pay_cv_rate` Nullable(Float32), 
    `search_visitor_count` Nullable(Int64), 
    `search_pay_buyer_count` Nullable(Int64)
)
ENGINE = MergeTree()
ORDER BY id
SETTINGS index_granularity = 8192
