ATTACH VIEW DimSpu
(
    `spu` Nullable(String), 
    `id` Int64, 
    `SPUKey` Int64, 
    `spu名称` Nullable(String), 
    `cat1` Nullable(String), 
    `cat2` Nullable(String), 
    `cat3` Nullable(String), 
    `cat4` Nullable(String), 
    `cat5` Nullable(String), 
    `supply_cycle` Nullable(Int64), 
    `min_order_count` Nullable(Float32), 
    `商品类型` Nullable(String), 
    `大类` Nullable(String), 
    `中类` Nullable(String), 
    `小类` Nullable(String), 
    `小小类` Nullable(String), 
    `子类` Nullable(String), 
    `吊牌价` Nullable(Float32), 
    `产品年` Nullable(Int64), 
    `产品季` Nullable(String), 
    `产品年季` Nullable(String), 
    `season_start_date` Nullable(Date), 
    `season_end_date` Nullable(Date), 
    `结构` Nullable(String), 
    `搭配` Nullable(String), 
    `面料` Nullable(String), 
    `袖长` Nullable(String), 
    `衣长` Nullable(String), 
    `衣型` Nullable(String), 
    `领型` Nullable(String), 
    `花色` Nullable(String), 
    `厚度` Nullable(String), 
    `裤长` Nullable(String), 
    `裤腰` Nullable(String), 
    `裤型` Nullable(String), 
    `裙型` Nullable(String), 
    `裙长` Nullable(String), 
    `款型` Nullable(String), 
    `元素` Nullable(String), 
    `大小` Nullable(String), 
    `面料/材质` Nullable(String), 
    `配套` Nullable(String), 
    `跟型` Nullable(String), 
    `扣头色` Nullable(String), 
    `宽度` Nullable(String), 
    `包型` Nullable(String), 
    `鞋型` Nullable(String), 
    `帽型` Nullable(String), 
    `扣头` Nullable(String), 
    `袜型` Nullable(String), 
    `围巾型` Nullable(String), 
    `鞋头` Nullable(String), 
    `鞋面` Nullable(String), 
    `筒高` Nullable(String), 
    `帮面` Nullable(String), 
    `鞋口` Nullable(String), 
    `特性` Nullable(String), 
    `内裤裤型` Nullable(String), 
    `杯型` Nullable(String), 
    `类型` Nullable(String), 
    `罩杯` Nullable(String), 
    `搭扣` Nullable(String), 
    `背部设计` Nullable(String), 
    `功能` Nullable(String), 
    `杯托` Nullable(String), 
    `版型` Nullable(String), 
    `腰头` Nullable(String), 
    `价格带` Nullable(String), 
    `利润模型` Nullable(String)
) AS
SELECT DISTINCT 
    p.spu AS spu, 
    m.id AS id, 
    m.id AS SPUKey, 
    spu_name AS `spu名称`, 
    cat1, 
    cat2, 
    cat3, 
    cat4, 
    cat5, 
    supply_cycle, 
    min_order_count, 
    p3 AS `商品类型`, 
    d1.category_name AS `大类`, 
    d2.category_name AS `中类`, 
    d3.category_name AS `小类`, 
    d4.category_name AS `小小类`, 
    d5.category_name AS `子类`, 
    tag_price AS `吊牌价`, 
    sale_year AS `产品年`, 
    sale_season AS `产品季`, 
    concat(toString(sale_year), sale_season) AS `产品年季`, 
    multiIf(sale_year = 9999, toDate('2099-01-01'), season_start_date) AS season_start_date, 
    multiIf(sale_year = 9999, toDate('2099-12-31'), season_end_date) AS season_end_date, 
    pp.p1 AS `结构`, 
    pp.p2 AS `搭配`, 
    pp.p3 AS `面料`, 
    pp.p4 AS `袖长`, 
    pp.p5 AS `衣长`, 
    pp.p6 AS `衣型`, 
    pp.p7 AS `领型`, 
    pp.p8 AS `花色`, 
    pp.p9 AS `厚度`, 
    pp.p10 AS `裤长`, 
    pp.p11 AS `裤腰`, 
    pp.p12 AS `裤型`, 
    pp.p13 AS `裙型`, 
    pp.p14 AS `裙长`, 
    pp.p15 AS `款型`, 
    pp.p16 AS `元素`, 
    pp.p17 AS `大小`, 
    pp.p18 AS `面料/材质`, 
    pp.p19 AS `配套`, 
    pp.p20 AS `跟型`, 
    pp.p21 AS `扣头色`, 
    pp.p22 AS `宽度`, 
    pp.p23 AS `包型`, 
    pp.p24 AS `鞋型`, 
    pp.p25 AS `帽型`, 
    pp.p26 AS `扣头`, 
    pp.p27 AS `袜型`, 
    pp.p28 AS `围巾型`, 
    pp.p29 AS `鞋头`, 
    pp.p30 AS `鞋面`, 
    pp.p31 AS `筒高`, 
    pp.p32 AS `帮面`, 
    pp.p33 AS `鞋口`, 
    pp.p34 AS `特性`, 
    pp.p35 AS `内裤裤型`, 
    pp.p36 AS `杯型`, 
    pp.p37 AS `类型`, 
    pp.p38 AS `罩杯`, 
    pp.p39 AS `搭扣`, 
    pp.p40 AS `背部设计`, 
    pp.p41 AS `功能`, 
    pp.p42 AS `杯托`, 
    pp.p43 AS `版型`, 
    pp.p44 AS `腰头`, 
    pp.p45 AS `价格带`, 
    pp.p46 AS `利润模型`
FROM spl_huigou.src_products AS p
ANY LEFT JOIN spl_huigou.src_product_design_props AS pp ON pp.spu = p.spu
ANY LEFT JOIN spl_huigou.src_products AS pc ON pc.spu = p.spu
ANY LEFT JOIN spl_huigou.src_product_levels AS d1 ON d1.category_code = pc.cat1
ANY LEFT JOIN spl_huigou.src_product_levels AS d2 ON d2.category_code = pc.cat2
ANY LEFT JOIN spl_huigou.src_product_levels AS d3 ON d3.category_code = pc.cat3
ANY LEFT JOIN spl_huigou.src_product_levels AS d4 ON d4.category_code = pc.cat4
ANY LEFT JOIN spl_huigou.src_product_levels AS d5 ON d5.category_code = pc.cat5
ANY LEFT JOIN spl_huigou.src_product_sale_seasons AS ps ON ps.sku = p.sku
ANY LEFT JOIN spl_huigou.mapping_keys AS m ON m.code = p.spu
