version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1qaz2wsx 
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
